name: AutoZombieSurvival
version: R-2021.08.27
author: D_Selon
website: https://blog.naver.com/cgko321
main: com.D_Selon.AutoZombieSurvival.DMain
commands:
  AutoZombieSurvival:
    aliases: [autozombiesurvival, AZS, azs]
    description: AutoZombieSurvival's main command.
    